# Generated by Django 5.2.7 on 2025-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('course', 'Course'), ('mentor', 'Mentor')], max_length=10)),
                ('item_id', models.UUIDField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
